name: e2e

on:
  deployment_status:

jobs:
  run-e2e:
    name: Playwright testing deployment ${{ github.event.deployment_status.target_url }}
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: corepack enable
      - run: pnpm --version
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Install react project dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Install e2e-tests dependencies
        run: cd e2e-tests && pnpm install --frozen-lockfile --prefer-offline

      - name: Install dependencies with Playwright
        run: |
          cd e2e-tests && pnpm playwright install --with-deps

      - name: Run tests
        run: cd e2e-tests && pnpm run test:e2e
        env:
          BASE_E2E_URL: ${{ github.event.deployment_status.target_url }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: reports
          path: e2e-tests/reports/
          retention-days: 7
